# Generated by Django 3.2.16 on 2022-12-29 17:23

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Careprovider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('business_name', models.CharField(max_length=35)),
                ('main_contact_name', models.CharField(max_length=35)),
                ('address_line1', models.CharField(max_length=50)),
                ('address_line2', models.CharField(max_length=50)),
                ('address_line3', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=6)),
                ('phone_number', models.IntegerField()),
                ('out_of_hours_phone_number', models.IntegerField()),
                ('email_address', models.CharField(max_length=50)),
                ('has_disabled_space', models.BooleanField()),
                ('careprovider_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Careseeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('careseeker_username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('address_line1', models.CharField(max_length=50)),
                ('address_line2', models.CharField(max_length=50)),
                ('address_line3', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=6)),
                ('home_phone_number', models.IntegerField()),
                ('mobile_phone_number', models.IntegerField()),
                ('email_address', models.CharField(max_length=50)),
                ('needs_assistance', models.BooleanField()),
                ('needs_disabled_space', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating_number', models.IntegerField()),
                ('title', models.CharField(max_length=35)),
                ('comment', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('ratings_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='caresearch.careprovider')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
