# Generated by Django 3.2.16 on 2022-12-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caresearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careseeker',
            name='needs_assistance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='careseeker',
            name='needs_disabled_space',
            field=models.BooleanField(default=False),
        ),
    ]
